const TRACKING_STEP_SECONDS = 60;

const TRACKING_STEPS = [
    "PLACED",
    "PAID",
    "RESERVED",
    "CONFIRMED",
    "PREPARING",
    "SHIPPED",
    "OUT_FOR_DELIVERY",
    "DELIVERED"
];

const TRACKING_STATUSES = [
    ...TRACKING_STEPS,
    "CANCELLED"
];

module.exports = {
    TRACKING_STEP_SECONDS,
    TRACKING_STEPS,
    TRACKING_STATUSES
};